#!/usr/bin/env python3
"""Create a conflict-free w8-core environment and verify the running browser."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import socket
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent
DEFAULT_ENV_PATH = ROOT / ".env"
NOVNC_PATH = "/vnc.html?resize=scale&autoconnect=1&path=websockify"


def read_env(path: Path) -> dict[str, str]:
    """Read the simple KEY=VALUE format used by this recorder."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key] = value
    return values


def port_is_available(port: int) -> bool:
    """Return whether an IPv4 loopback TCP port can be published by Docker."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            listener.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


def choose_port(preferred: int, used: set[int]) -> int:
    """Use the familiar port when free, otherwise ask the OS for a free port."""
    if preferred not in used and port_is_available(preferred):
        used.add(preferred)
        return preferred
    while True:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
            listener.bind(("127.0.0.1", 0))
            selected = int(listener.getsockname()[1])
        if selected not in used:
            used.add(selected)
            return selected


def docker_container_exists(name: str) -> bool:
    completed = subprocess.run(
        ["docker", "inspect", name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return completed.returncode == 0


def unique_container_name(base: str) -> str:
    if not docker_container_exists(base):
        return base
    sequence = 2
    while docker_container_exists(f"{base}-{sequence}"):
        sequence += 1
    return f"{base}-{sequence}"


def runtime_identity(root: Path = ROOT) -> str:
    return hashlib.sha256(str(root).encode("utf-8")).hexdigest()[:8]


def write_env(path: Path, values: dict[str, str]) -> None:
    content = f"""# Generated by ./browser-runtime configure.
# This file contains credentials and is intentionally ignored by Git.
IMAGE={values['IMAGE']}
COMPOSE_PROJECT_NAME={values['COMPOSE_PROJECT_NAME']}
CONTAINER_NAME={values['CONTAINER_NAME']}

CDP_HOST_PORT={values['CDP_HOST_PORT']}
NOVNC_HOST_PORT={values['NOVNC_HOST_PORT']}
VNC_HOST_PORT={values['VNC_HOST_PORT']}
RUNNER_NOVNC_URL={values['RUNNER_NOVNC_URL']}

OPENAI_API_KEY={values['OPENAI_API_KEY']}
OPENAI_MODEL={values['OPENAI_MODEL']}

CHROMIUM_HEADLESS=0
CHROMIUM_RESET_PROFILE=0
"""
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8")
    os.chmod(temporary, 0o600)
    temporary.replace(path)


def configure(env_path: Path, refresh_ports: bool) -> int:
    existing = read_env(env_path)
    if env_path.exists() and not refresh_ports:
        print(f"Configuration already exists: {env_path}")
        print("Nothing was overwritten. Use --refresh-ports only after stopping the service.")
        print_runtime_urls(existing)
        return 0

    suffix = runtime_identity()
    used: set[int] = set()
    cdp_port = choose_port(49335, used)
    novnc_port = choose_port(16191, used)
    vnc_port = choose_port(15911, used)
    container_name = existing.get("CONTAINER_NAME")
    if not container_name:
        container_name = unique_container_name(f"w8-core-browser-{suffix}")
    values = {
        "IMAGE": existing.get("IMAGE", "wootzapp/w8-core:latest"),
        "COMPOSE_PROJECT_NAME": existing.get(
            "COMPOSE_PROJECT_NAME", f"w8-recorder-{suffix}"
        ),
        "CONTAINER_NAME": container_name,
        "CDP_HOST_PORT": str(cdp_port),
        "NOVNC_HOST_PORT": str(novnc_port),
        "VNC_HOST_PORT": str(vnc_port),
        "RUNNER_NOVNC_URL": f"http://127.0.0.1:{novnc_port}{NOVNC_PATH}",
        "OPENAI_API_KEY": existing.get(
            "OPENAI_API_KEY", "replace-with-your-openai-api-key"
        ),
        "OPENAI_MODEL": existing.get(
            "OPENAI_MODEL", "replace-with-a-supported-model-name"
        ),
    }
    env_path.parent.mkdir(parents=True, exist_ok=True)
    write_env(env_path, values)
    print(f"Created conflict-free browser configuration: {env_path}")
    print_runtime_urls(values)
    print("Edit OPENAI_API_KEY and OPENAI_MODEL before running a model-driven task.")
    return 0


def required_port(values: dict[str, str], key: str) -> int:
    try:
        port = int(values[key])
    except (KeyError, ValueError) as error:
        raise RuntimeError(f"{key} is missing or is not an integer") from error
    if not 1 <= port <= 65535:
        raise RuntimeError(f"{key} is outside the valid TCP port range")
    return port


def get_json(url: str) -> dict[str, object]:
    with urllib.request.urlopen(url, timeout=5) as response:
        return json.loads(response.read().decode("utf-8"))


def get_page(url: str) -> int:
    with urllib.request.urlopen(url, timeout=5) as response:
        response.read(256)
        return int(response.status)


def run(command: Iterable[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(command),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def print_runtime_urls(values: dict[str, str]) -> None:
    if "NOVNC_HOST_PORT" in values:
        print(f"Local browser: http://127.0.0.1:{values['NOVNC_HOST_PORT']}{NOVNC_PATH}")
    if "CDP_HOST_PORT" in values:
        print(f"Host CDP: http://127.0.0.1:{values['CDP_HOST_PORT']}")


def status(env_path: Path) -> int:
    values = read_env(env_path)
    if not values:
        raise RuntimeError(f"configuration not found: {env_path}")
    container_name = values.get("CONTAINER_NAME", "w8-core-browser-engine")
    cdp_port = required_port(values, "CDP_HOST_PORT")
    novnc_port = required_port(values, "NOVNC_HOST_PORT")

    inspected = run(["docker", "inspect", container_name])
    if inspected.returncode != 0:
        raise RuntimeError(f"container does not exist: {container_name}")
    document = json.loads(inspected.stdout)[0]
    state = document.get("State", {})
    running = bool(state.get("Running"))
    health = (state.get("Health") or {}).get("Status", "not-configured")
    print(f"Container: {container_name}")
    print(f"Running: {'yes' if running else 'no'}")
    print(f"Health: {health}")
    if not running:
        raise RuntimeError("browser container is not running")
    if health not in {"healthy", "not-configured"}:
        raise RuntimeError(f"browser container is not ready: {health}")

    version = get_json(f"http://127.0.0.1:{cdp_port}/json/version")
    browser_version = version.get("Browser", "unknown")
    print(f"CDP: ready ({browser_version})")

    novnc_url = f"http://127.0.0.1:{novnc_port}{NOVNC_PATH}"
    if get_page(novnc_url) != 200:
        raise RuntimeError("noVNC did not return HTTP 200")
    print(f"noVNC: ready ({novnc_url})")

    agent_browser = run(
        ["docker", "exec", container_name, "agent-browser", "--version"]
    )
    if agent_browser.returncode != 0:
        detail = agent_browser.stderr.strip() or agent_browser.stdout.strip()
        raise RuntimeError(f"agent-browser check failed: {detail}")
    print(f"agent-browser: {agent_browser.stdout.strip()}")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Configure and verify the w8-core browser used by the task recorder"
    )
    parser.add_argument("--env-file", type=Path, default=DEFAULT_ENV_PATH)
    subparsers = parser.add_subparsers(dest="command", required=True)
    configure_parser = subparsers.add_parser(
        "configure", help="create an isolated .env with available host ports"
    )
    configure_parser.add_argument(
        "--refresh-ports",
        action="store_true",
        help="preserve credentials and identity while selecting new free ports",
    )
    subparsers.add_parser("status", help="verify container, CDP, noVNC, and agent-browser")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    env_path = args.env_file.resolve()
    try:
        if args.command == "configure":
            return configure(env_path, args.refresh_ports)
        return status(env_path)
    except (RuntimeError, OSError, urllib.error.URLError, json.JSONDecodeError) as error:
        print(f"browser runtime error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
